apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-$ID 
  namespace: yurisanspeur
spec:
  parallelism: 1
  template:
    metadata:
      name: test-job-$ID 
      labels:
        app: test-job-$ID 
    spec:
      initContainers:
        # This container's purpose is to securely clone a desired git repo to EmptyDir volume
       - name: git-clone
         image: alpine/git
         args:
           - clone
           - --single-branch
           - --branch
           - MgO_run_firetask
           - https://github.com/ulissigroup/al_mlp.git
           - /home/jovyan
         volumeMounts:
          - name: git-repo
            mountPath: /home/jovyan
      restartPolicy: OnFailure 
      containers:
       - name: test-job-$ID 
         image: ulissigroup/kubeflow_vasp:atomate_stack_mlp_test_python
         imagePullPolicy: Always
         env:
         - name: JOB_ID
           value: "$ID"
         command: ["/bin/bash", "-c"]
         args:
         - echo Launching all processes... &&
           ./run_fireworks.sh
         volumeMounts:
           - mountPath: /home/jovyan/
             name: git-repo 
           - mountPath: /home/jovyan/atomate
             subPath: atomate
             name: workspace-atomate
         resources:
           limits:
             cpu: "20"
             memory: 100G
           requests:
             cpu: "20"
             memory: 100G
      volumes:
        - name: git-repo
          emptyDir: {}
        - name: workspace-atomate
          persistentVolumeClaim:
            claimName: workspace-atomate


