apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment 
  namespace: yurisanspeur
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-deployment
  template:
    metadata:
      name: test-deployment 
      labels:
        app: test-deployment 
    spec:
      restartPolicy: Always 
      containers:
       - name: test-deployment 
         image: ulissigroup/kubeflow_vasp:atomate_stack_mlp_test_python
         imagePullPolicy: Always
         env:
         - name: JOB_ID
           value: "10"
         command: ["/bin/bash", "-c"]
         args:
         - echo Launching all processes... &&
           ./run_fireworks.sh
           # - echo Launching Dask Local Cluster... &&
           #   python start_scheduler.py &&
           #   echo Sleeping... &&
           #   sleep 10 &&
           #   echo Done sleeping. &&
           #   python run_firetask.py &&
           #   echo Done running firetasks.
         volumeMounts:
           - mountPath: /home/jovyan/
             name: github-workspace 
           - mountPath: /home/jovyan/atomate
             subPath: atomate
             name: workspace-atomate
         resources:
           limits:
             cpu: "20"
             memory: 100G
           requests:
             cpu: "20"
             memory: 100G
               #      volumes:
               #      - name: workspace 
               #        persistentVolumeClaim:
               #          claimName: workspace-atomate
      volumes:
        - name: github-workspace
          gitRepo:
            repository: https://github.com/ulissigroup/al_mlp.git
            revision: MgO_run_firetask
            directory: .
        - name: workspace-atomate
          persistentVolumeClaim:
            claimName: workspace-atomate


