apiVersion: batch/v1
kind: Job
metadata:
  name: test-deployment 
  namespace: yurisanspeur
spec:
  parallelism: 1
  template:
    metadata:
      name: test-deployment 
      labels:
        app: test-deployment 
    spec:
      restartPolicy: OnFailure 
      containers:
       - name: test-deployment 
         image: ulissigroup/kubeflow_vasp:atomate_stack_mlp_test_python
         imagePullPolicy: Always
         env:
         - name: JOB_ID
           value: "$ID"
         command: ["/bin/bash", "-c"]
         args:
         - echo Launching all processes... &&
           ./run_fireworks.sh
         volumeMounts:
           - mountPath: /home/jovyan/
             name: github-workspace 
           - mountPath: /home/jovyan/atomate
             subPath: atomate
             name: workspace-atomate
         resources:
           limits:
             cpu: "20"
             memory: 100G
           requests:
             cpu: "20"
             memory: 100G
               #      volumes:
               #      - name: workspace 
               #        persistentVolumeClaim:
               #          claimName: workspace-atomate
      volumes:
        - name: github-workspace
          gitRepo:
            repository: https://github.com/ulissigroup/al_mlp.git
            revision: MgO_run_firetask
            directory: .
        - name: workspace-atomate
          persistentVolumeClaim:
            claimName: workspace-atomate


