apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-$ID 
  namespace: yurisanspeur
spec:
  parallelism: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      name: test-job-$ID 
      labels:
        app: test-job-$ID 
    spec:
      #affinity:
      #  nodeAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #      nodeSelectorTerms:
      #      - matchExpressions:
      #        - key: "nvidia.com/gpu.product"
      #          operator: "DoesNotExist"
      nodeName: heroic-imp 
      initContainers:
        # This container's purpose is to securely clone a desired git repo to EmptyDir volume
       - name: git-clone
         image: alpine/git
         args:
           - clone
           - --single-branch
           - --branch
           - MgO_run_firetask
           - https://github.com/ulissigroup/al_mlp.git
           - /data
         volumeMounts:
          - name: git-repo
            mountPath: /data
         resources:
           requests:
             cpu: 1
             memory: 1Gi
           limits:
             cpu: 1
             memory: 1Gi
      restartPolicy: Never
      containers:
       - name: test-job-$ID 
         image: ulissigroup/kubeflow_vasp:atomate_stack_mlp_test_python
         workingDir: /home/jovyan/al_mlp_repo
         imagePullPolicy: Always
         env:
         - name: JOB_ID
           value: "$ID"
         command: ["/bin/bash", "-c"]
         args:
         - echo Adding all jobs to the queue... &&
           ./add_fw.sh
         volumeMounts:
           - mountPath: /home/jovyan/al_mlp_repo
             name: git-repo 
           - mountPath: /home/jovyan/
             name: workspace-atomate
         resources:
           limits:
             cpu: "0.5"
             memory: 0.5G
           requests:
             cpu: "0.5"
             memory: 0.5G
      volumes:
        - name: git-repo
          emptyDir: {}
        - name: workspace-atomate
          persistentVolumeClaim:
            claimName: workspace-atomate


